### ISSUE TITLE
Add .travis.yml

### ISSUE THREAD

**Issue by srhodgson** [srhodgson/TestMakerFreeWebApp#2]
Once the initial version of the application has been created and tested we then need to add a .travis.yml file so that Travis-CI is able to correctly build and subsequently deploy our app to azure.

A basic outline of the file should be as follows:

```yaml
language: csharp
mono: none
dotnet: <need to confirm runtime>
script:
  - dotnet restore 

deploy:
  provider: azure_web_apps
  username: azure_deployment_user       # If AZURE_WA_USERNAME isn't set
  password: azure_deployment_password   # If AZURE_WA_PASSWORD isn't set
  site: azure_deployment_sitename       # If AZURE_WA_SITE isn't set
  slot: azure_deployment_slotname       # (optional) If AZURE_WA_SLOT isn't set
```

It will also be necesarry to complete some further changes on azure
